// ===================== PRESET DATA =====================
const PRESET_WORDS = [
  {word:"smuggle",phonetic:"/ˈsmʌɡ(ə)l/",zh:"vt. 走私；偷运",en:"import or export without paying customs duties",example:"They deny conspiring together to smuggle drugs."},
  {word:"flourish",phonetic:"/ˈflʌrɪʃ/",zh:"v. 繁荣，茂盛；茁壮成长；挥舞；炫耀",en:"a showy gesture",example:"He opened the door for her with a flourish."},
  {word:"reserve",phonetic:"/rɪˈzɜːv/",zh:"v. 预订；储备；留出；n. 储备量；自然保护区；预备队",en:"formality and propriety of manner",example:"I'll reserve a table for five."},
  {word:"dimensional",phonetic:"/daɪˈmenʃən(ə)l/",zh:"adj. 空间的；尺寸的",en:"of or relating to dimensions",example:"This is a three-dimensional crystal."},
  {word:"gravel",phonetic:"/ˈɡræv(ə)l/",zh:"n. 碎石；砂砾",en:"rock fragments and pebbles",example:"The car drew up with a crunch of gravel."},
  {word:"insulation",phonetic:"/ˌɪnsjuˈleɪʃ(ə)n/",zh:"n. 绝缘；隔离，孤立",en:"the state of being isolated or detached",example:"Better insulation of your home will help to reduce heating bills."},
  {word:"improvise",phonetic:"/ˈɪmprəvaɪz/",zh:"vt. 即兴创作；即兴表演；临时凑合",en:"perform without preparation",example:"There isn't much equipment. We're going to have to improvise."},
  {word:"hesitation",phonetic:"/ˌhezɪˈteɪʃn/",zh:"n. 犹豫",en:"indecision in speech or action",example:"She agreed without the slightest hesitation."},
  {word:"undermine",phonetic:"/ˌʌndəˈmaɪn/",zh:"vt. 破坏，渐渐破坏；挖掘地基",en:"destroy property or hinder normal operations",example:"He accused me of slandering him and trying to undermine his position."},
  {word:"eliminate",phonetic:"/ɪˈlɪmɪneɪt/",zh:"vt. 消除；排除",en:"terminate or take out",example:"This diet claims to eliminate toxins from the body."},
  {word:"exclude",phonetic:"/ɪkˈskluːd/",zh:"vt. 排除；排斥；拒绝接纳；逐出",en:"prevent from being included or considered or accepted",example:"She gets very upset if I exclude her from anything."},
  {word:"laundry",phonetic:"/ˈlɔːndri/",zh:"n. 洗衣店，洗衣房；要洗的衣服",en:"garments or white goods that can be cleaned by laundering",example:"He worked in the laundry at Oxford prison."},
  {word:"apparently",phonetic:"/əˈpærəntli/",zh:"adv. 显然地；似乎，表面上",en:"from appearances alone",example:"He paused, apparently lost in thought."},
  {word:"gelatin",phonetic:"/ˈdʒelətɪn/",zh:"n. 明胶；动物胶；胶制品",en:"a colorless water-soluble glutinous protein obtained from animal tissues",example:"Gelatin has a long history of use as a gelling agent by the food industry."},
  {word:"stimulate",phonetic:"/ˈstɪmjuleɪt/",zh:"vt. 刺激；鼓舞，激励",en:"act as a stimulant",example:"These businesses stimulate the creation of local jobs."},
  {word:"fuel",phonetic:"/ˈfjuːəl/",zh:"n. 燃料；刺激因素；vt. 给…提供燃料；煽动",en:"a substance that can be consumed to produce energy",example:"The boiler uses solid fuel."},
  {word:"operational",phonetic:"/ˌɒpəˈreɪʃən(ə)l/",zh:"adj. 操作的；运作的",en:"pertaining to a process or series of actions for achieving a result",example:"The new airport is now fully operational."},
  {word:"distribute",phonetic:"/dɪˈstrɪbjuːt/",zh:"vt. 分配；散布；分开；把…分类",en:"administer or bestow, as in small portions",example:"Aid workers helped distribute corn, milk and other staples."},
  {word:"intend",phonetic:"/ɪnˈtend/",zh:"vt. 打算；想要；意指",en:"have in mind as a purpose",example:"I don't intend staying long."},
  {word:"empirical",phonetic:"/ɪmˈpɪrɪk(ə)l/",zh:"adj. 经验主义的，完全根据经验的；实证的",en:"derived from experiment and observation rather than theory",example:"There is no empirical evidence to support his thesis."},
  {word:"probation",phonetic:"/prəˈbeɪʃ(ə)n/",zh:"n. 试用；缓刑；查验",en:"a trial period during which your character and abilities are tested",example:"He was given two years' probation."},
  {word:"depression",phonetic:"/dɪˈpreʃn/",zh:"n. 沮丧；抑郁症；洼地；不景气；低气压区",en:"a mental state characterized by a pessimistic sense of inadequacy",example:"Depression is treatable."},
  {word:"proximity",phonetic:"/prɒkˈsɪməti/",zh:"n. 接近，邻近；接近度，距离",en:"the property of being close together",example:"He became aware of the proximity of the Afghans."},
  {word:"attention",phonetic:"/əˈtenʃ(ə)n/",zh:"n. 注意力；关心；立正！",en:"the process whereby a person concentrates on some features of the environment",example:"My shoes caught his attention."},
  {word:"factual",phonetic:"/ˈfæktʃuəl/",zh:"adj. 事实的；真实的",en:"existing in act or fact",example:"The essay contains a number of factual errors."},
  {word:"acclaim",phonetic:"/əˈkleɪm/",zh:"v. 称赞；为……喝彩，向……欢呼",en:"enthusiastic approval",example:"The novel received great acclaim."},
  {word:"carry",phonetic:"/ˈkæri/",zh:"vt. 拿，扛；携带；支持；搬运",en:"move while supporting",example:"He was carrying a large bag."},
  {word:"devastate",phonetic:"/ˈdevəsteɪt/",zh:"vt. 毁灭；毁坏",en:"cause extensive destruction or ruin utterly",example:"The city was devastated by the earthquake."},
  {word:"response",phonetic:"/rɪˈspɒns/",zh:"n. 响应；反应；回答",en:"a bodily process occurring due to the effect of some stimulus or agent",example:"His response was immediate."},
  {word:"dull",phonetic:"/dʌl/",zh:"adj. 钝的；迟钝的；无趣的；呆滞的；阴暗的",en:"lacking in liveliness or animation",example:"The lecture was dull and boring."},
  {word:"basis",phonetic:"/ˈbeɪsɪs/",zh:"n. 基础；底部；主要成分；基本原则或原理",en:"the fundamental assumptions from which something is begun",example:"We meet on a regular basis."},
  {word:"tropical",phonetic:"/ˈtrɒpɪk(ə)l/",zh:"adj. 热带的；热情的；酷热的",en:"relating to or situated in the tropics",example:"They enjoy the tropical climate."},
  {word:"rumour",phonetic:"/ˈruːmə(r)/",zh:"n. 谣言",en:"gossip passed around by word of mouth",example:"I heard a rumour that she's leaving."},
  {word:"endeavour",phonetic:"/ɪnˈdevə(r)/",zh:"v. 努力，尽力",en:"attempt by employing effort",example:"We will endeavour to finish on time."},
  {word:"address",phonetic:"/əˈdres/",zh:"n. 地址；演讲；称呼；v. 处理；演说",en:"the place where a person or organization can be found",example:"Please write your address clearly."},
  {word:"payment",phonetic:"/ˈpeɪmənt/",zh:"n. 付款，支付；报酬；偿还",en:"a sum of money paid or a claim discharged",example:"Payment must be made in advance."},
  {word:"superb",phonetic:"/suːˈpɜːb/",zh:"adj. 极好的；华丽的；宏伟的",en:"of surpassing excellence",example:"The food was superb."},
  {word:"intention",phonetic:"/ɪnˈtenʃ(ə)n/",zh:"n. 意图；目的；意向",en:"an anticipated outcome that is intended",example:"I have no intention of leaving."},
  {word:"demonstrate",phonetic:"/ˈdemənstreɪt/",zh:"vt. 证明；展示；论证",en:"give an exhibition of to an interested audience",example:"The study demonstrates the link between poverty and malnutrition."},
  {word:"agenda",phonetic:"/əˈdʒendə/",zh:"n. 议程；日常工作事项；日程表",en:"a list of matters to be taken up",example:"The next item on the agenda is the budget."},
  {word:"illuminate",phonetic:"/ɪˈluːmɪneɪt/",zh:"vt. 阐明，说明；照亮；使灿烂",en:"make lighter or brighter",example:"The room was illuminated by candles."},
  {word:"slim",phonetic:"/slɪm/",zh:"adj. 苗条的；修长的；微小的；差的",en:"being of delicate or slender build",example:"She has a slim figure."},
  {word:"warrant",phonetic:"/ˈwɒrənt/",zh:"n. 根据；证明；正当理由；委任状",en:"a writ from a court commanding police to perform specified acts",example:"Police issued a warrant for his arrest."},
  {word:"optimism",phonetic:"/ˈɒptɪmɪz(ə)m/",zh:"n. 乐观；乐观主义",en:"the optimistic feeling that all is going to turn out well",example:"There are grounds for cautious optimism."},
  {word:"rank",phonetic:"/ræŋk/",zh:"n. 排；等级；军衔；队列",en:"relative status",example:"She achieved the rank of colonel."},
  {word:"avail",phonetic:"/əˈveɪl/",zh:"v. 有助于；（使）对某人有利",en:"a means of serving",example:"All our efforts availed us little."},
  {word:"block",phonetic:"/blɒk/",zh:"n. 块；街区；大厦；障碍物",en:"a solid piece of something",example:"There's a post office just around the block."},
  {word:"administrative",phonetic:"/ədˈmɪnɪstrətɪv/",zh:"adj. 管理的，行政的",en:"of or relating to or responsible for administration",example:"She works in an administrative role."},
  {word:"frustrating",phonetic:"/frʌˈstreɪtɪŋ/",zh:"adj. 令人沮丧的",en:"discouraging by hindering",example:"It's frustrating when you can't remember a word."},
  {word:"resistant",phonetic:"/rɪˈzɪstənt/",zh:"adj. 抵抗的，反抗的；顽固的",en:"relating to or conferring immunity",example:"These plants are resistant to drought."},
  {word:"overdue",phonetic:"/ˌəʊvəˈdjuː/",zh:"adj. 过期的；迟到的；未兑的",en:"past due; not paid at the scheduled time",example:"The library books are overdue."},
  {word:"impressive",phonetic:"/ɪmˈpresɪv/",zh:"adj. 感人的；令人钦佩的；给人以深刻印象的",en:"making a strong or vivid impression",example:"The performance was impressive."},
  {word:"analysis",phonetic:"/əˈnæləsɪs/",zh:"n. 分析；分解；验定",en:"an investigation of the component parts of a whole",example:"We carried out a detailed analysis."},
  {word:"verdict",phonetic:"/ˈvɜːdɪkt/",zh:"n. 结论；裁定",en:"findings of a jury on issues of fact for decision",example:"The jury returned a verdict of not guilty."},
  {word:"refresher",phonetic:"/rɪˈfreʃə(r)/",zh:"n. 可提神的人或物；补习课程；清凉饮料",en:"a course that reviews and updates a topic",example:"I took a refresher course in French."},
  {word:"blaze",phonetic:"/bleɪz/",zh:"v. 燃烧；发光；怒视；宣扬",en:"a strong flame that burns brightly",example:"The fire blazed all night."},
  {word:"misjudge",phonetic:"/ˌmɪsˈdʒʌdʒ/",zh:"vi. 判断错",en:"judge incorrectly",example:"I misjudged the distance and fell short."},
  {word:"pregnant",phonetic:"/ˈpreɡnənt/",zh:"adj. 怀孕的；富有意义的",en:"carrying developing offspring within the body",example:"She is six months pregnant."},
  {word:"unyielding",phonetic:"/ʌnˈjiːldɪŋ/",zh:"adj. 不屈的；坚强的；不易弯曲的",en:"stubbornly unyielding",example:"He faced the challenge with unyielding determination."},
  {word:"exterior",phonetic:"/ɪkˈstɪəriə(r)/",zh:"adj. 外部的，外面的，外在的；外界的",en:"the region that is outside of something",example:"The exterior of the building was impressive."},
  {word:"approve",phonetic:"/əˈpruːv/",zh:"vt. 批准；赞成；为…提供证据",en:"give sanction to",example:"The committee approved the plan."},
  {word:"client",phonetic:"/ˈklaɪənt/",zh:"n. 客户；顾客；委托人",en:"someone who pays for goods or services",example:"Our clients include several major companies."},
  {word:"vernacular",phonetic:"/vəˈnækjʊlə(r)/",zh:"adj. 本国的；地方的；用本地语写成的",en:"the everyday speech of the people",example:"He wrote in the vernacular."},
  {word:"compare",phonetic:"/kəmˈpeə(r)/",zh:"v. 比较，对比；与……类似",en:"examine and note the similarities or differences of",example:"Compare the two versions carefully."},
  {word:"transparent",phonetic:"/trænsˈpærənt/",zh:"adj. 透明的；显然的；坦率的；易懂的",en:"transmitting light; able to be seen through with clarity",example:"The glass was completely transparent."},
  {word:"deputy",phonetic:"/ˈdepjuti/",zh:"n. 代理人，代表",en:"a person appointed to represent or act on behalf of others",example:"He was appointed deputy headteacher."},
  {word:"fraud",phonetic:"/frɔːd/",zh:"n. 欺骗；骗子；诡计",en:"intentional deception resulting in injury to another person",example:"He was convicted of fraud."},
  {word:"bind",phonetic:"/baɪnd/",zh:"vi. 结合；装订；有约束力；过紧",en:"stick to firmly",example:"Add an egg to bind the mixture."},
  {word:"fragrance",phonetic:"/ˈfreɪɡrəns/",zh:"n. 香味，芬芳",en:"a distinctive odor that is pleasant",example:"The fragrance of roses filled the room."},
  {word:"acute",phonetic:"/əˈkjuːt/",zh:"adj. 严重的，急性的；敏锐的；激烈的；尖声的",en:"demonstrating ability to recognize or draw fine distinctions",example:"He has acute hearing."},
  {word:"image",phonetic:"/ˈɪmɪdʒ/",zh:"n. 影像；想象；肖像；偶像",en:"a visual representation produced on a surface",example:"The image was clear and sharp."}
];
